import os
from crewai import Agent, Task, Crew, LLM
from crewai_tools import FileWriterTool, FileReadTool
from git import Repo

# Prevent telemetry and OpenAI lookups
os.environ["OTEL_SDK_DISABLED"] = "true" 
os.environ["OPENAI_API_KEY"] = "NA"      

# 1. DIRECTORY & GIT SETUP
WORKING_DIR = "./workspace"
if not os.path.exists(WORKING_DIR):
    os.makedirs(WORKING_DIR)

try:
    repo = Repo('.') 
except:
    repo = Repo.init('.')

file_writer = FileWriterTool(directory=WORKING_DIR)
file_reader = FileReadTool(directory=WORKING_DIR)

# 2. LOCAL BRAINS (Modern LLM Class)
# ---------------------------------------------------------
# We define these as LLM objects to encapsulate the base_url
logic_llm_config = LLM(
    model="ollama/llama3.2:latest",
    base_url="http://localhost:11434"
)

coding_llm_config = LLM(
    model="ollama/phi3:mini",
    base_url="http://localhost:11434"
)

# 3. AGENTS
# ---------------------------------------------------------
pm = Agent(
    role='Product Manager',
    goal='Architect features and create technical specs for {user_request}.',
    backstory='Senior PM. You ensure the Full Stack Dev knows exactly what to build.',
    llm=logic_llm_config,
    verbose=True,
    allow_delegation=False
)

full_stack_dev = Agent(
    role='Full Stack Engineer',
    goal='Develop logic and save files specifically to the workspace folder.',
    backstory='Senior Dev. You write code and save it using the FileWriterTool.',
    llm=coding_llm_config,
    tools=[file_writer, file_reader],
    verbose=True,
    allow_delegation=False
)

ciso = Agent(
    role='CISO',
    goal='Audit the workspace folder for security issues.',
    backstory='Security Auditor. You review the code generated by the Dev.',
    llm=logic_llm_config,
    tools=[file_reader],
    verbose=True,
    allow_delegation=False
)

# 4. THE 24/7 LOOP
# ---------------------------------------------------------
def run_ai_factory():
    while True:
        user_request = input("\n[MANAGER] Enter feature request: ")
        if user_request.lower() == 'exit': break

        plan_task = Task(
            description=f"Plan this feature: {user_request}. Define CSV structures and fuzzy matching logic using libraries like 'thefuzz' or 'difflib'.",
            expected_output="Detailed spec for the developer.",
            agent=pm
        )

        build_task = Task(
            description="Build the Python tool based on the PM spec. Use the FileWriterTool to save the script to the './workspace' directory.",
            expected_output="Functional Python script inside the workspace folder.",
            agent=full_stack_dev,
            context=[plan_task]
        )

        audit_task = Task(
            description="Read the generated script in the './workspace' directory and ensure no malicious code or hardcoded keys exist.",
            expected_output="Security report and approval.",
            agent=ciso,
            context=[build_task]
        )

        crew = Crew(
            agents=[pm, full_stack_dev, ciso], 
            tasks=[plan_task, build_task, audit_task],
            verbose=True
        )
        
        result = crew.kickoff(inputs={'user_request': user_request})

        try:
            repo.git.add(A=True)
            repo.index.commit(f"AI Update: {user_request}")
            print("\n--- Git Snapshot Saved ---")
        except Exception as e:
            print(f"Git Note: {e}")

if __name__ == "__main__":
    run_ai_factory()